name: Friends
version: '${project.version}'
main: net.dxzzz.friends.Friends
depend: [PlaceholderAPI,HeadDatabase]

commands:
  hy:
    description: "组队系统"
    permission: Friends.Normal
    usage: "§3§l⚎⚎⚎⚎⚎⚎⚎⚎ §6Dxzzz.Net §f- §9组队喇叭 §3§l⚎⚎⚎⚎⚎⚎⚎⚎\n
            §3 > §e/hy js <玩家>  §3§l➽  §a接受好友邀请\n
            §3 > §e/hy lb <页数>  §3§l➽  §a好友列表\n
            §3 > §e/hy sc <玩家>  §3§l➽  §a删除好友\n
            §3 > §e/hy tj <玩家>  §3§l➽  §a添加好友\n
            §3 > §c你的好友位上限为20人！好友菜单可购买解锁更多好友位！\n
            §3 > §e/fm§7快速私聊 §e/fr§7回复和继续聊天 §e/fg§7全局聊天\n
            §3 > §7私聊可使用TAB补全好友ID\n
            §3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎"

  fg:
    description: "好友-全局聊天"
    permission: Friends.Normal
    usage: "§3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎ §6Dxzzz.Net §f- §9好友全局聊天 §3§l⚎⚎⚎⚎⚎⚎⚎⚎\n
            §3 > §e/fg <内容>  §3§l➽  §a发送全局聊天\n
            §3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎"

  fr:
    description: "好友-快速回复"
    permission: Friends.Normal
    usage: "§3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎ §6Dxzzz.Net §f- §9好友快速回复 §3§l⚎⚎⚎⚎⚎⚎⚎⚎\n
            §3 > §e/fr <内容>  §3§l➽  §a快速回复\n
            §3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎"
  fm:
    description: "好友-私聊消息"
    permission: Friends.Normal
    usage: "§3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎ §6Dxzzz.Net §f- §9好友私聊消息 §3§l⚎⚎⚎⚎⚎⚎⚎⚎\n
            §3 > §e/fm <玩家> <内容>  §3§l➽  §a好友私聊\n
            §3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎"


  hyop:
    description: "好友系统管理"
    permission: Friends.Admin
    usage: "§3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎ §6Dxzzz.Net §f- §9好友系统管理 §3§l⚎⚎⚎⚎⚎⚎⚎⚎\n
            §3 > §e/hyop vip <玩家>  §3§l➽  §a给某人开通好友位扩展权限\n
            §3§l⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎⚎"

permissions:
  Friends.Normal:
    default: true
  Friends.Admin:
    default: op
